logging:
  config: classpath:logback-spring.xml
server:
  port: 8080
  servlet:
    context-path: /api/demo
spring:
  application:
    name: hello-spring3.0
  profiles:
    active: dev,personal
  ## Spring Cloud 配置 使用 Nacos 作为注册中心
  cloud:
    nacos:
      discovery:
        enabled: true
        metadata:
          content-path: ${server.servlet.context-path}/actuator
        namespace: ${personal_namespace}
        server-addr: ${nacos_addr}
        # 权重配置，本地dev开发时如果注册到测试测试环境的 namespace 时,请设置为0，不要接收其他服务的请求，影响线上测试
        weight: 0F
      password: ${nacos_username}
      username: ${nacos_password}