logging:
  config: classpath:logback-spring.xml
server:
  port: 8080
  servlet:
    context-path: /api/demo
spring:
  application:
    name: hello-spring3.0
  profiles:
    active: dev
## Spring Cloud 配置 使用 Nacos 作为注册中心
  cloud:
    nacos:
      discovery:
        enabled: true
        metadata:
          content-path: ${server.servlet.context-path}/actuator
        namespace: 867085f0-760b-4a1e-8b9c-48c8de3195f7
        server-addr: ${nacos_addr}
      password: ${nacos_username}
      username: ${nacos_password}